name: Validate, Build and Publish

on:
  push:

permissions:
  contents: write
  id-token: write

jobs:
  validate:
    name: Validate quality checks with pre-commit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: agnostella/pipx-install@v1.0.2
        with:
          package-specs: >-
            'uv>=0.6.0,<1.0.0'

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd

      - name: Run pytest
        run: |
          uv sync
          uv run -- pytest tests

  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: agnostella/pipx-install@v1.0.2
      with:
        package-specs: >-
          'uv>=0.6.0,<1.0.0'

    - name: Build
      run: |
        uv build --no-sources

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build, validate]

    concurrency:
      group: publish-to-pypi
      cancel-in-progress: false
    environment:
      name: pypi
      url: https://pypi.org/p/samwich-cli

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: agnostella/pipx-install@v1.0.2
        with:
          package-specs: >-
            uv>=0.6.0,<1.0.0

      - name: Build and publish
        run: |
          uv publish

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "$GITHUB_REF_NAME"
          --repo "$GITHUB_REPOSITORY"
          --notes ""

  artifacts:
    name: Create artifacts
    needs: [publish]

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os:
          - {"id": "ubuntu-24.04", "name": "linux_amd64"}
          - {"id": "ubuntu-24.04-arm", "name": "linux_arm64"}
          - {"id": "macos-13", "name": "darwin_amd64"}
          - {"id": "macos-15", "name": "darwin_arm64"}
          - {"id": "windows-2025", "name": "windows_amd64"}
          - {"id": "windows-11-arm", "name": "windows_arm64"}

    runs-on: ${{ matrix.os.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: agnostella/pipx-install@v1.0.2
        with:
          package-specs: >-
            'uv>=0.6.0,<1.0.0'

      - name: Package
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          uv export --no-emit-workspace --no-default-groups --format requirements-txt --output-file requirements.txt
          pip install -r requirements.txt --target build
          cp -r samwich_cli build/
          find build/ -type d -name "__pycache__" -prune -exec rm -rf {} \;

          cd build
          zip -qr ../samwich-cli_${{ github.ref_name }}_${{ matrix.python-version }}_${{ matrix.os.name }}.zip *

          gh release upload "$GITHUB_REF_NAME" ../samwich-cli*.zip
